#############################################################
#
# ARE - Policy Engine
#
#############################################################

##############################
# Score thresholds
##############################

WATCH_SCORE=20

TEMP_BAN_SCORE=60

PERMANENT_BAN_SCORE=100

##############################
# Category thresholds
##############################

RECON_THRESHOLD=80

EXPLOIT_THRESHOLD=40

CREDENTIAL_THRESHOLD=30

PROTOCOL_THRESHOLD=20

BOT_THRESHOLD=50

##############################
# Ban times
##############################

WATCH_TIMEOUT=0

TEMP_BAN_TIMEOUT=86400

PERMANENT_BAN_TIMEOUT=0
