#!/bin/bash

DEBUG=0

LOG_LEVEL=INFO

VERSION="1.1.0"

MODE="production"

##################################################
# Paths
##################################################

ARE_HOME="/opt/are"
ARE_DATA="/var/lib/are"

ARE_BIN="$ARE_HOME/are.sh"
ARE_CONFIG="$ARE_HOME/config/config.conf"
ARE_POLICY_CONFIG="$ARE_HOME/config/policy.conf"
ARE_WHITELIST="$ARE_HOME/config/whitelist.conf"

ARE_SENSOR_DIR="$ARE_HOME/sensors"
ARE_POLICY_DIR="$ARE_HOME/policy"
ARE_DASHBOARD_DIR="$ARE_HOME/dashboard"
ARE_TESTING_DIR="$ARE_HOME/testing"
ARE_TMP_DIR="$ARE_HOME/tmp"

##################################################
# IPSET
##################################################

FILTER_SET4="are-filter"
FILTER_SET6="are-filter6"

BAN_SET4="are-blacklist"
BAN_SET6="are-blacklist6"

##################################################
# Database
##################################################

DB_FILE="$ARE_DATA/are.db"
DB_TIMEOUT=5000
DB_DEBUG=0

##################################################
# Whitelist
##################################################

WHITELIST="$ARE_WHITELIST"

##################################################
# Logging
##################################################

ARE_LOG_DIR="/var/log/are"
ARE_LOG_FILE="$ARE_LOG_DIR/are.log"
LOGTAG="ARE"
